#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Rebase Projector Sources

# Trigger on demand
on:
  workflow_dispatch:

jobs:
  rebase-projector-sources:
    name: Rebase Projector Sources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ GITHUB_TOKEN }}
      - name: Git configure
        run: |
          git config --global user.email "vzhukovs+sync-projector@redhat.com"
          git config --global user.name "Eclipse Che Sync"
      - name: Add upstream and fetch remotes
        run: |
          git remote add upstream-projector-client https://github.com/JetBrains/projector-client
          git fetch upstream-projector-client master
          git remote add upstream-projector-server https://github.com/JetBrains/projector-server
          git fetch upstream-projector-server master
      - name: Rebase Projector sources
        run: |
          ./projector.sh rebase
      - name: Validate Docker build
        run: |
          docker build -f build/dockerfiles/projector-server-builder.Dockerfile .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.1
